version: '3'
services:
  # Next.js アプリ
  app:
    build: .
    volumes:
      - .:/app # 開発用マウント
    ports:
      - '3000:3000'
    command: npm run dev
    environment:
      - NEXT_TURBO=0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ricechain?schema=public
      - SESSION_PASSWORD=iWasBORntoloVeYOUwITheVERySinGleBEaToFMyliFE
    depends_on:
      - db # db が立ち上がってから dev を開始

  # PostgreSQL
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ricechain
    ports:
      - '5432:5432' # ホストから直接触る場合に便利
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
